### PR TITLE
Fix build on Ubuntu 24.04

### PR DESCRIPTION
**Pull request by mkindahl**
Fix a couple of header includes that prevented a clean build on Ubuntu 24.04.

Disable-check: force-changelog-file

### CODE REVIEW

**Comment by mkindahl** [comment]
I am not sure why this fixes some issues with Ubuntu 22.04. Maybe the original author @erimatnor can shed some light here.

**Comment by fabriziomello** [comment]
What exactly we're fixing here? Do u have any CI link and/or logs/messages about this unclean build on ubuntu 24.04?

**Review by svenklemm — APPROVED** [review]

**Comment by svenklemm** [comment]
Maybe we should enforce source file name to be unique in general, would improve convenience in some cases.

**Comment by akuzm** [comment]
> Maybe we should enforce source file name to be unique in general, would improve convenience in some situations.

Let's require explicit path instead, like PG does? It is unique.

**Comment by mkindahl** [comment]
> > Maybe we should enforce source file name to be unique in general, would improve convenience in some situations.
> 
> Let's require explicit path instead, like PG does? It is unique.

This approach is quite commonly used, especially in large codebases, so you have to use `-Isrc` (and `-Itsl/src` I suppose) and never include subdirectories (so we have to remove some `include_directories` in each subdir and replace the includes) and you ensure that all includes are relative to `src` and `tsl/src`. It would still allow include using quotes from the current directory, but at least it avoids some confusion.

I would definitely prefer this.

Problem is that we have split the sources into the "tsl" and "non-tsl" trees, and it would be better to have something like "src/tsl", so this might require a bigger rewrite, which I am not sure is a good idea.

**Comment by mkindahl** [comment]
Closing this as obsolete for now.

**Pull request closed without merging**
