### PR TITLE
Add test for repair table script

### PR DESCRIPTION
**Pull request by mkindahl**
This commit copies the repair query into a separate file and turns
it into a procedure. This will allow the repair query to be tested
separately using `pg_regress`. It also adds a test script for the
repair procedure and will remove different sorts of dimensions and see
that they can be properly repaired.

It also contain a fix for the timestamp parsing query that prevented it
from handling all timestamp formats and a fix so that if many chunks refer to the same dimension slice, it might generate duplicate rows.

### CODE REVIEW

**Comment by mkindahl** [comment]
There is one unfortunate situation in that we need to have two copies of the repair script. I fear that might result in mistakes when one script is updated but not the other.

**Comment by mkindahl** [comment]
> It doesn't seem right to me that the update script is tested in a regression test. Why isn't it part of the update test?
> 
> The odd thing is that this is a script that needs to run only once on upgrades of specific versions of the database, so it doesn't seem right that this has to run as part of our standard regression suite. It also doesn't test that the update script actually works during an update to a new version of the extension.

Not sure I follow. Pg_regress will start a clean server and test that the repair script will repair tables, so it's perfect for testing the repair script. It is not a complete test that the update script works, it just test that it can repair the dimension slice table.

We already have update tests, but they cannot catch all kind of problems. They just test that a correct installation can be updated.

**Comment by svenklemm** [comment]
I agree with @erimatnor the script is run when upgrading from 1.7.1 to 1.7.2 so there is no need in maintaining it and adjusting it to catalog changes because it needs to run in the 1.7.1 environment therefore regression tests are not the right place.

**Comment by mkindahl** [comment]
Closing.

**Pull request closed without merging**
