### PR TITLE
Fix coverity warning about null pointer dereference

### PR DESCRIPTION
**Pull request by svenklemm**
While the coverity warning is a false positive since rte->relkind is always either RELKIND_RELATION or RELKIND_VIEW this might not hold always true. This patch changes the if check to an Ensure and removes some nesting in the function.

Disable-check: force-changelog-file

### CODE REVIEW

**Comment by svenklemm** [comment]
Might want to review with whitespace ignored as it doesnt handle the changed indentation very well.

**Review by fabriziomello — APPROVED** [review]

**Comment by fabriziomello** [comment]
Do we need to backport it to 2.15.x?

**Comment by svenklemm** [comment]
Did you run coverity on 2.15.x? If the trigger is in 2.15.x then we should include it. But overall it's mostly cosmetic change so we could pull it in even if coverity doesnt complain on 2.15.x

**Comment by fabriziomello** [comment]
> Did you run coverity on 2.15.x? If the trigger is in 2.15.x then we should include it. But overall it's mostly cosmetic change so we could pull it in even if coverity doesnt complain on 2.15.x

I didn't but the code that generated this coverity issue is present on 2.15.x branch so would be good to include it.

**Pull request merged**
