### PR TITLE
Update emacs configuration

### PR DESCRIPTION
**Pull request by epgts**
Use postgres for sql-mode, which makes it easier to connect to local
postgresql with C-c C-z and also sets up postgresql extensions for
font-lock.

Copy the 4-space tab-width setting to diff-mode so that, for example,
diffs of lines containing 18 TABs don't display with 144-space indent.

Disable-check: force-changelog-file

### CODE REVIEW

**Review by mkindahl — APPROVED** [review]

**Comment by epgts** [comment]
Looks like I need a second approver...

Also, tests just don't want to pass, and one check is even insisting I update the Changelog.

Where's the force button? :)

Thanks!

**Review by fabriziomello — APPROVED** [review]

**Comment by epgts** [comment]
What's it going to take to get this merged?  I have some real changes I'm working on, and sometimes I lose this local edit, making my life sad, or accidentally push it, making my reviewers' lives sad :)

> Looks like I need a second approver...
> 
> Also, tests just don't want to pass, and one check is even insisting I update the Changelog.
> 
> Where's the force button? :)

Thanks!

**Comment by mkindahl** [comment]
> What's it going to take to get this merged? I have some real changes I'm working on, and sometimes I lose this local edit, making my life sad, or accidentally push it, making my reviewers' lives sad :)
> 
> > Looks like I need a second approver...
> > Also, tests just don't want to pass, and one check is even insisting I update the Changelog.
> > Where's the force button? :)
> 
> Thanks!

If you look at the error message that the Changelog message prints, it will show you how to do it.

```
PR does not add a change log file in .unlreased/ folder
Check .unlreased/template.rfc822 for the format of the change log file.

To disable changelog updated check, add this trailer to pull request message:

Disable-check: force-changelog-file

Trailers follow RFC2822 conventions, so no whitespace
before field name and the check is case-insensitive for
both the field name and the field body.
```

**Comment by epgts** [comment]
> Disable-check: force-changelog-file

Thanks!  I set that and reran the check but it still fails:  https://github.com/timescale/timescaledb/actions/runs/5046313658/jobs/9077139162

**Comment by epgts** [comment]
> > Disable-check: force-changelog-file
> 
> Thanks! I set that and reran the check but it still fails: https://github.com/timescale/timescaledb/actions/runs/5046313658/jobs/9077139162

Never mind!  That was the wrong run.  The rerun passed :upside_down_face: 

Thanks!

**Pull request merged**
