### PR TITLE
Add support for PG13

### LINKED ISSUE #2434: v13 support
Hi,

PostgreSQL 13 is due tomorrow. When will you release v13 compatible version?

Regards, Devrim

### PR DESCRIPTION
**Pull request by svenklemm**
Fixes #2434

### CODE REVIEW

**Comment by fvannee** [comment]
Thanks @svenklemm for this draft PR!
I have tested this branch on PG13 and haven't found any issues so far related to PG13 with the basic Timescale functionality (hypertables, chunk exclusion, copy, etc.). I haven't tested continuous aggregates and distributed hypertables.
I'll let you know if I find anything.

**Comment by mfreed** [comment]
Hi folks, for anybody else who is/can test from source, would appreciate more eyes on this, and very much welcome community testers.  Thanks!

**Comment by Rogach** [comment]
I tested this PR on my system and everything seems to work correctly so far.

**Comment by moorchegue** [comment]
Wanted to try and test this branch. Getting this when trying to build against 13.1:

```
...
[ 34%] Building C object src/CMakeFiles/timescaledb.dir/partitioning.c.o
In file included from /usr/include/string.h:519,
                 from /usr/include/postgresql/server/c.h:61,
                 from /usr/include/postgresql/server/postgres.h:46,
                 from /tmp/makepkg/timescaledb/src/timescaledb-2.0.0pg13/src/partitioning.c:6:
In function ‘strncpy’,
    inlined from ‘ts_partitioning_info_create’ at /tmp/makepkg/timescaledb/src/timescaledb-2.0.0pg13/src/partitioning.c:187:2:
/usr/include/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound 64 equals destination size [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strncpy’,
    inlined from ‘ts_partitioning_info_create’ at /tmp/makepkg/timescaledb/src/timescaledb-2.0.0pg13/src/partitioning.c:188:2:
/usr/include/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound 64 equals destination size [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strncpy’,
    inlined from ‘ts_partitioning_info_create’ at /tmp/makepkg/timescaledb/src/timescaledb-2.0.0pg13/src/partitioning.c:196:2:
/usr/include/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound 64 equals destination size [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/timescaledb.dir/build.make:628: src/CMakeFiles/timescaledb.dir/partitioning.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1039: src/CMakeFiles/timescaledb.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

Any ideas?

**Comment by mkindahl** [comment]
> Wanted to try and test this branch. Getting this when building against 13.1:
> 
> ```
> ...
> [ 34%] Building C object src/CMakeFiles/timescaledb.dir/partitioning.c.o
> In file included from /usr/include/string.h:519,
>                  from /usr/include/postgresql/server/c.h:61,
>                  from /usr/include/postgresql/server/postgres.h:46,
>                  from /tmp/makepkg/timescaledb/src/timescaledb-2.0.0pg13/src/partitioning.c:6:
> In function ‘strncpy’,
>     inlined from ‘ts_partitioning_info_create’ at /tmp/makepkg/timescaledb/src/timescaledb-2.0.0pg13/src/partitioning.c:187:2:
> /usr/include/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound 64 equals destination size [-Werror=stringop-truncation]
>   106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In function ‘strncpy’,
>     inlined from ‘ts_partitioning_info_create’ at /tmp/makepkg/timescaledb/src/timescaledb-2.0.0pg13/src/partitioning.c:188:2:
> /usr/include/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound 64 equals destination size [-Werror=stringop-truncation]
>   106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In function ‘strncpy’,
>     inlined from ‘ts_partitioning_info_create’ at /tmp/makepkg/timescaledb/src/timescaledb-2.0.0pg13/src/partitioning.c:196:2:
> /usr/include/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound 64 equals destination size [-Werror=stringop-truncation]
>   106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> cc1: all warnings being treated as errors
> make[2]: *** [src/CMakeFiles/timescaledb.dir/build.make:628: src/CMakeFiles/timescaledb.dir/partitioning.c.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1039: src/CMakeFiles/timescaledb.dir/all] Error 2
> make: *** [Makefile:149: all] Error 2
> ```
> 
> Any ideas?

These are warnings turned into errors because `WARNINGS_AS_ERRORS` is by default `ON`. You can turn them off by calling `cmake` with `-DWARNINGS_AS_ERRORS=OFF`, which should allow you to compile the code.

**Comment by svenklemm** [comment]
Closing this since the code changes were done in smaller PRs and are all merged to master

**Pull request closed without merging**
