### PR TITLE
Fix caggs on caggs tests on PG15

### PR DESCRIPTION
**Pull request by fabriziomello**
PR #4668 introduced the Hierarchical Continuous Aggregates (aka Continuous Aggregate on top of another Continuous Aggregate) but unfortunately we miss to fix the regression tests on PG15.

### CODE REVIEW

**Review by sb230132 — APPROVED** [review]
Their seems to be tests failing with trailing whitespaces.
Please fix them as well.

**Review by jnidzwetzki — APPROVED** [review]
There is a typo in the commit message (`Hierarchival` -> `Hierarchical`), rest LGTM.

**Comment by fabriziomello** [comment]
> There is a typo in the commit message (`Hierarchival` -> `Hierarchical`), rest LGTM.

Fixed thanks!

**Comment by fabriziomello** [comment]
> Their seems to be tests failing with trailing whitespaces. Please fix them as well.

Fixed thanks!

**Pull request merged**
