### PR TITLE
Revised the get_general_index_definition function

### PR DESCRIPTION
**Pull request by bricklen**
Revised the get_general_index_definition function to handle cases where indexes have definitions other than just 'CREATE INDEX'.
Handles mixed-case identifiers correctly too.

```
\d "Foo"
        Table "public.Foo"
   Column    |  Type   | Modifiers
-------------+---------+-----------
 foo_id      | integer |
 foo_some_id | integer |
 person_id   | integer |
 Some ColumN | text    |
Indexes:
    "foo_SomeColum Index" UNIQUE, btree ("Some ColumN")
    "Foo_foo_some_id_IDX" btree (foo_some_id)


select oid,relname from pg_class where relname in ('Foo','foo_SomeColum Index','Foo_foo_some_id_IDX');

  oid   |       relname
--------+---------------------
 100798 | Foo
 175162 | foo_SomeColum Index
 175163 | Foo_foo_some_id_IDX


-- Index "foo_SomeColum Index"
-- This is the original function, it fails because the index def is not "CREATE INDEX ..."
select test_original_get_general_index_definition(175162,100798); 
ERROR:  Cannot process index with definition (no index name match) CREATE UNIQUE INDEX "foo_SomeColum Index" ON /*TABLE_NAME*/ USING btree ("Some ColumN")
CONTEXT:  PL/pgSQL function test_original_get_general_index_definition(regclass,regclass) line 29 at RAISE

select test_revised_get_general_index_definition(175162,100798);
              test_revised_get_general_index_definition
----------------------------------------------------------------------------------
 CREATE UNIQUE INDEX /*INDEX_NAME*/ ON /*TABLE_NAME*/ USING btree ("Some ColumN")


-- Index "Foo_foo_some_id_IDX"
select test_original_get_general_index_definition(175163,100798);
            test_original_get_general_index_definition
-------------------------------------------------------------------------
 CREATE INDEX /*INDEX_NAME*/ ON /*TABLE_NAME*/ USING btree (foo_some_id)

select test_revised_get_general_index_definition(175163,100798);
          test_revised_get_general_index_definition
-------------------------------------------------------------------------
 CREATE INDEX /*INDEX_NAME*/ ON /*TABLE_NAME*/ USING btree (foo_some_id)
```

### CODE REVIEW

**Comment by mfreed** [comment]
Hi @bricklen, our CLA is now available for review/signing.  You can access it in the above "Details" link.  Thanks for your patience while we got this in place!

**Comment by bricklen** [comment]
Hi, it says `license/cla — Contributor License Agreement is not signed yet.` above. Is it waiting on you guys, or did my attempt submit that CLA fail in some way? I didn't see any errors and now I can't seem to edit it so I had assumed the CLA was signed properly.

**Comment by mfreed** [comment]
@bricklen Sorry for the trouble.  I see your information in the database; not sure why the webhook/API doesn't seem to be working (cla-assistant.io, run by SAP).  Will look into this.

**Comment by RobAtticus** [comment]
For some reason the CLA status is not updating, but we see you having agreed so I'm going to merge this. Thanks!

**Comment by RobAtticus** [comment]
Only thing I can think of is maybe the commit email you used is not associated with your github account, so the CLA assistant can't properly match you?

**Comment by bricklen** [comment]
Hmm, yeah, that very well may be it. Good thinking!

**Pull request merged**
