### PR TITLE
Fix casing in telemetry

### PR DESCRIPTION
**Pull request by JLockerman**
should be `apache_only` not `ApacheOnly`

### CODE REVIEW

**Comment by RobAtticus** [comment]
I'm confused, I'm not actually seeing a casing issue? It appears you just added a new macro and changing the value from one (non-existent?) macro to another.

**Comment by RobAtticus** [comment]
Also, why should it be `apache_only`? Not clear to me.

**Comment by JLockerman** [comment]
@RobAtticus in the telemetry the `edition` field will say `apache_only` for an Apache build instead of `ApacheOnly`. This was done on request from @solugebefola to make the metrics more consistent.

**Comment by RobAtticus** [comment]
Some explanation in the commit would be good then.

**Pull request merged**
