### PR TITLE
Remove unit tests and sql/setup

### PR DESCRIPTION
**Pull request by cevian**
Remove unit tests because most of our testing is in regression tests
anyway and regression tests are better integrated with the Postgres
extension workflow. sql/setup scripts were old and not used except
for unit testing.

### CODE REVIEW

**Comment by cevian** [comment]
@olofr you wrote the sql/setup scripts I think. Please make sure I did the right thing by removing them.

**Comment by herrold** [comment]
It may be that these are no longer needed unit tests, but the work there looks like a nice 'end to end' integration test set.  Perhaps it is just not in the right place?

**Comment by cevian** [comment]
I am not sure I know what you mean by 'end to end' IT. If you mean the full read-write cycle I think this is now covered by regression test like [this](https://github.com/timescale/timescaledb/blob/master/test/sql/insert_single.sql) (the corresponding golden file is [here](https://github.com/timescale/timescaledb/blob/master/test/expected/insert_single.out)). But maybe I am missing something. Wouldn't want to overlook some testing. Thanks for the input!

**Comment by herrold** [comment]
In development, having a unit test around and automatically run against a check-in helps one avoid inadvertently breaking a known state of the software.  The problem is that the time it takes to perform such, or setting up the testing harness (here, using a socket, having database installed, and so forth) are not cost free. Also sometimes tests rot and are no longer germane to any live code.  Not relevant here as the database back-end is not going away

Then once one feels that one is done with some code, one does integration testing of the carious parts in a chain, and looks for breakage.  It often suggests over-looked unit tests in a specification.  Bug #20 which indicates that there is an ACL problem in connecting with the database, reflects this.  An approach to this would be to add a unit test which 'drops permissions' down to a non universal and all rights' user, to the less dangerous 'unprivileged end user' before running the test in question.  Again, solving the unit test and running it at least occasionally, permits one to know that some other change has not allowed a old bug to creep back in

Closer still to a finished product release is 'end to end' testing, there all tests are run, specified inputs are fed in, and expected results captured, examined, and the desired result confirmed

Volumes have been written on TDD and testing, but one takeaway in my experience, is that an accurate test (one that does not yield false positives or false negatives) is usually worth keeping -- and run at least occasionally, and always at release time.  See for more:
   https://developers.google.com/google-test-automation-conference/2014/presentations

There is no cost to placing a working set of tests in a less frequently used place (move from unit, to integration, or end_to_end sub-directory under the ./test/ hierarchy comes to mind) ), but even though in the git history, as a practical matter, 'out of sight will be out of mind' and someone will want a good test in the future, institutional memory will not remember it, and a wheel will be needless re-invented

**Comment by olofr** [comment]
If you want to remove it all it looks right. I would prefer if this PR would include the corresponding regression tests though ?

**Comment by cevian** [comment]
@erimatnor @olofr Added a regression test to replace hash_test.sql. The other test (chunk_test.sql) is already covered in regression tests. Those were the only two unit tests we actually had, AFAIK. The rest of the code was boilerplate setup, teardown stuff. @herrold Thanks for you discussion above, it was helpful in pushing me to determine how to do unit tests going forward. I think the test I added in my second commit shows how to write "unit-style" tests within the regression framework Postgres has established for extensions. I actually think this way is easier to read (it uses the ASSERT command supplied in PLPGSQL instead of a third-party unit testing framework with it's own set of custom functions you need to learn)  and is also much less verbose to write. It also now runs these tests as part of our CI pipeline.

**Comment by olofr** [comment]
Are the queries of no value any more ?

**Comment by cevian** [comment]
@olofr which queries? I couldn't actually find the tests for them (think they were in the old, defunct ioql format and were deleted before this PR). But I very well could be missing something?

**Comment by olofr** [comment]
Ah, I just saw the expected outputs. Didn't know the queries had gone before. Don't we need such tests though ?

**Comment by cevian** [comment]
I don't think so. They were very ioql specific. All tests regarding queries in the new system should be in the regression tests (sql_query*).

**Pull request merged**
