### PR TITLE
Inherit CFLAGS from postgresql

### PR DESCRIPTION
**Pull request by svenklemm**
There are quite a few compiler flags that need to be identical
between postgresql and timescaledb otherwise there will be
seemingly unexplainable failures during execution.
We inherit all CFLAGS from postgresql except those starting
with -W as we have our own set of warning options.

### CODE REVIEW

**Comment by mfundul** [comment]
Shouldn't we do the same with `-O` flags?

**Comment by svenklemm** [comment]
> Shouldn't we do the same with `-O` flags? What about compiling with debugging symbols?

Not sure what you are asking but with this patch we will inherit -g and -O flags from postgresql.

**Comment by mfundul** [comment]
> 
> 
> > Shouldn't we do the same with `-O` flags? What about compiling with debugging symbols?
> 
> Not sure what you are asking but with this patch we will inherit -g and -O flags from postgresql.

What if postgreSQL has no debug flags, but I want to enable those for timescaledb? Is this a problem?

**Comment by svenklemm** [comment]
> > > Shouldn't we do the same with `-O` flags? What about compiling with debugging symbols?
> > 
> > 
> > Not sure what you are asking but with this patch we will inherit -g and -O flags from postgresql.
> 
> What if postgreSQL has no debug flags, but I want to enable those for timescaledb? Is this a problem?

No its not and you can supply additional CFLAGS when calling bootstrap. This patch is about flags that produce code that is not binary compatible if they are not the same. Some examples of those:
```
man gcc |grep "not binary compatible"
           Warning: the -fsso-struct switch causes GCC to generate code that is not binary compatible with code generated without it if the specified endianness is not the native endianness of the target.
           Warning: code compiled with the -fpcc-struct-return switch is not binary compatible with code compiled with the -freg-struct-return switch.  Use it to conform to a non-default application binary interface.
           Warning: code compiled with the -freg-struct-return switch is not binary compatible with code compiled with the -fpcc-struct-return switch.  Use it to conform to a non-default application binary interface.
           Warning: the -fshort-enums switch causes GCC to generate code that is not binary compatible with code generated without that switch.  Use it to conform to a non-default application binary interface.
           Warning: the -fshort-wchar switch causes GCC to generate code that is not binary compatible with code generated without that switch.  Use it to conform to a non-default application binary interface.
           Warning: the -fpack-struct switch causes GCC to generate code that is not binary compatible with code generated without that switch.  Additionally, it makes the code suboptimal.  Use it to conform to a non-default
           Warning: the -fleading-underscore switch causes GCC to generate code that is not binary compatible with code generated without that switch.  Use it to conform to a non-default application binary interface.  Not all
           Moreover, code compiled with -ftrampolines and code compiled with -fno-trampolines are not binary compatible if nested functions are present.  This option must therefore be used on a program-wide basis and be manipulated
           Warning: The -mone-byte-bool switch causes GCC to generate code that is not binary compatible with code generated without that switch.  Using this switch may require recompiling all other modules in a program, including
           Warning: if you use the -malign-double switch, structures containing the above types are aligned differently than the published application binary interface specifications for the x86-32 and are not binary compatible
```

**Review by mfundul — APPROVED** [review]

**Review by mkindahl — COMMENTED** [review]
Have you tested this with `clang`?

**Comment by mkindahl** [comment]
> > > > Shouldn't we do the same with `-O` flags? What about compiling with debugging symbols?
> > > 
> > > 
> > > Not sure what you are asking but with this patch we will inherit -g and -O flags from postgresql.
> > 
> > 
> > What if postgreSQL has no debug flags, but I want to enable those for timescaledb? Is this a problem?
> 
> No its not and you can supply additional CFLAGS when calling bootstrap. This patch is about flags that produce code that is not binary compatible if they are not the same. Some examples of those:
> 
> ```
> man gcc |grep "not binary compatible"
>            Warning: the -fsso-struct switch causes GCC to generate code that is not binary compatible with code generated without it if the specified endianness is not the native endianness of the target.
>            Warning: code compiled with the -fpcc-struct-return switch is not binary compatible with code compiled with the -freg-struct-return switch.  Use it to conform to a non-default application binary interface.
>            Warning: code compiled with the -freg-struct-return switch is not binary compatible with code compiled with the -fpcc-struct-return switch.  Use it to conform to a non-default application binary interface.
>            Warning: the -fshort-enums switch causes GCC to generate code that is not binary compatible with code generated without that switch.  Use it to conform to a non-default application binary interface.
>            Warning: the -fshort-wchar switch causes GCC to generate code that is not binary compatible with code generated without that switch.  Use it to conform to a non-default application binary interface.
>            Warning: the -fpack-struct switch causes GCC to generate code that is not binary compatible with code generated without that switch.  Additionally, it makes the code suboptimal.  Use it to conform to a non-default
>            Warning: the -fleading-underscore switch causes GCC to generate code that is not binary compatible with code generated without that switch.  Use it to conform to a non-default application binary interface.  Not all
>            Moreover, code compiled with -ftrampolines and code compiled with -fno-trampolines are not binary compatible if nested functions are present.  This option must therefore be used on a program-wide basis and be manipulated
>            Warning: The -mone-byte-bool switch causes GCC to generate code that is not binary compatible with code generated without that switch.  Using this switch may require recompiling all other modules in a program, including
>            Warning: if you use the -malign-double switch, structures containing the above types are aligned differently than the published application binary interface specifications for the x86-32 and are not binary compatible
> ```

I get the following flags when running `pg_config`. They do not contain any of the flags that are binary incompatible (according to the list above, not sure if there are more flags that are binary incompatible).

```
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer
```

Neither of these flags cause binary incompatible builds. AFAICT, for extensions to work with binary incompatible compile flags, these flags need to be in `CFLAGS_SL`, not `CFLAGS` (which seems to be used only for building the server). If the ABI is different between a shared library and the server, things will behave strangely, so it seems that any such flag *has* to be in `CFLAGS_SL`. 

```
--cflags
    Print the value of the CFLAGS variable that was used for building PostgreSQL. This shows C compiler switches.
--cflags_sl
    Print the value of the CFLAGS_SL variable that was used for building PostgreSQL. This shows extra C compiler switches used for building shared libraries.
```

**Comment by svenklemm** [comment]
> > ```
> > man gcc |grep "not binary compatible"
> >            Warning: the -fsso-struct switch causes GCC to generate code that is not binary compatible with code generated without it if the specified endianness is not the native endianness of the target.
> >            Warning: code compiled with the -fpcc-struct-return switch is not binary compatible with code compiled with the -freg-struct-return switch.  Use it to conform to a non-default application binary interface.
> >            Warning: code compiled with the -freg-struct-return switch is not binary compatible with code compiled with the -fpcc-struct-return switch.  Use it to conform to a non-default application binary interface.
> >            Warning: the -fshort-enums switch causes GCC to generate code that is not binary compatible with code generated without that switch.  Use it to conform to a non-default application binary interface.
> >            Warning: the -fshort-wchar switch causes GCC to generate code that is not binary compatible with code generated without that switch.  Use it to conform to a non-default application binary interface.
> >            Warning: the -fpack-struct switch causes GCC to generate code that is not binary compatible with code generated without that switch.  Additionally, it makes the code suboptimal.  Use it to conform to a non-default
> >            Warning: the -fleading-underscore switch causes GCC to generate code that is not binary compatible with code generated without that switch.  Use it to conform to a non-default application binary interface.  Not all
> >            Moreover, code compiled with -ftrampolines and code compiled with -fno-trampolines are not binary compatible if nested functions are present.  This option must therefore be used on a program-wide basis and be manipulated
> >            Warning: The -mone-byte-bool switch causes GCC to generate code that is not binary compatible with code generated without that switch.  Using this switch may require recompiling all other modules in a program, including
> >            Warning: if you use the -malign-double switch, structures containing the above types are aligned differently than the published application binary interface specifications for the x86-32 and are not binary compatible
> > ```
> 
> I get the following flags when running `pg_config`. They do not contain any of the flags that are binary incompatible (according to the list above, not sure if there are more flags that are binary incompatible).

These were  just examples and  which ones are relevant depend not only on your compiler but also your platform. 
> ```
> CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer
> ```
> 
> Neither of these flags cause binary incompatible builds. AFAICT, for extensions to work with binary incompatible compile flags, these flags need to be in `CFLAGS_SL`, not `CFLAGS` (which seems to be used only for building the server).
This is not true.  -fstack-protector-strong needs to be inherited on 32-bit otherwise you'll get random segfaults on i386.
> ```
> --cflags
>     Print the value of the CFLAGS variable that was used for building PostgreSQL. This shows C compiler switches.
> --cflags_sl
>     Print the value of the CFLAGS_SL variable that was used for building PostgreSQL. This shows extra C compiler switches used for building shared libraries.
> ```
> 
> If the ABI is different between a shared library and the server, things will behave strangely, so it seems that any such flag _has_ to be in `CFLAGS_SL` or else any build of shared libraries in PG will not work.

No it doesnt if the library uses the same CFLAGS.

**Comment by mkindahl** [comment]
> Have you tested this with `clang`?

As you mentioned on Slack, you did test with `clang`.

**Review by mkindahl — APPROVED** [review]

**Review by gayyappan — APPROVED** [review]

**Comment by mkindahl** [comment]
> > > ```
> > > man gcc |grep "not binary compatible"
> > >            Warning: the -fsso-struct switch causes GCC to generate code that is not binary compatible with code generated without it if the specified endianness is not the native endianness of the target.
> > >            Warning: code compiled with the -fpcc-struct-return switch is not binary compatible with code compiled with the -freg-struct-return switch.  Use it to conform to a non-default application binary interface.
> > >            Warning: code compiled with the -freg-struct-return switch is not binary compatible with code compiled with the -fpcc-struct-return switch.  Use it to conform to a non-default application binary interface.
> > >            Warning: the -fshort-enums switch causes GCC to generate code that is not binary compatible with code generated without that switch.  Use it to conform to a non-default application binary interface.
> > >            Warning: the -fshort-wchar switch causes GCC to generate code that is not binary compatible with code generated without that switch.  Use it to conform to a non-default application binary interface.
> > >            Warning: the -fpack-struct switch causes GCC to generate code that is not binary compatible with code generated without that switch.  Additionally, it makes the code suboptimal.  Use it to conform to a non-default
> > >            Warning: the -fleading-underscore switch causes GCC to generate code that is not binary compatible with code generated without that switch.  Use it to conform to a non-default application binary interface.  Not all
> > >            Moreover, code compiled with -ftrampolines and code compiled with -fno-trampolines are not binary compatible if nested functions are present.  This option must therefore be used on a program-wide basis and be manipulated
> > >            Warning: The -mone-byte-bool switch causes GCC to generate code that is not binary compatible with code generated without that switch.  Using this switch may require recompiling all other modules in a program, including
> > >            Warning: if you use the -malign-double switch, structures containing the above types are aligned differently than the published application binary interface specifications for the x86-32 and are not binary compatible
> > > ```
> > 
> > 
> > I get the following flags when running `pg_config`. They do not contain any of the flags that are binary incompatible (according to the list above, not sure if there are more flags that are binary incompatible).
> 
> These were just examples and which ones are relevant depend not only on your compiler but also your platform.
> 
> > ```
> > CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer
> > ```
> > 
> > 
> > Neither of these flags cause binary incompatible builds. AFAICT, for extensions to work with binary incompatible compile flags, these flags need to be in `CFLAGS_SL`, not `CFLAGS` (which seems to be used only for building the server).
> 
> This is not true. -fstack-protector-strong needs to be inherited on 32-bit otherwise you'll get random segfaults on i386.

Do you have a link to such a segfault? Would be interesting to see what it is.

The stack protector flag adds extra checking code to the beginning and end of the functions generated, but it does not affect the ABI. However, if adding the flag solves the issue, let's just add it.

> 
> > ```
> > --cflags
> >     Print the value of the CFLAGS variable that was used for building PostgreSQL. This shows C compiler switches.
> > --cflags_sl
> >     Print the value of the CFLAGS_SL variable that was used for building PostgreSQL. This shows extra C compiler switches used for building shared libraries.
> > ```
> > 
> > 
> > If the ABI is different between a shared library and the server, things will behave strangely, so it seems that any such flag _has_ to be in `CFLAGS_SL` or else any build of shared libraries in PG will not work.
> 
> No it doesnt if the library uses the same CFLAGS.

That is true, so approving.

**Pull request merged**
