### PR TITLE
Add release pipeline that build Docker image

### PR DESCRIPTION
**Pull request by mkindahl**
This commit add a release pipeline for patch releases that currently
can only be triggered manually. The release pipeline currently build a
docker image and push it to DockerHub but is intended to be extended
with the other jobs for publishing other artifacts.

The `Dockerfile.alpine` and `Dockerfile.bitnami` in this commit are
versions of the Docker files currently used for releases but adapted
to build directly from the repository and hence do not need to pull
specific versions from the git repositories and also have some 
dependencies removed that were not needed when building from the 
repository.

The workflow uses the official GitHub Actions published by Docker to 
build and publish the Docker image and also add a check that the 
Dockerfiles build with the source code to capture any changes in 
dependencies.

### CODE REVIEW

**Comment by NunoFilipeSantos** [comment]
To be discussed next Monday.

**Review by afiskon — APPROVED** [review]

**Comment by mkindahl** [comment]
Converting to draft and will add the following:

- Add build procedure for Debian outside the repository as separate actions
- Add build procedure for RPM outside the repository as separate actions
- Add support for platforms available for master branch (adding pipeline to to other branches will be done separately).
- Optionally add support for generating Docker images.

**Comment by mkindahl** [comment]
This release pipeline now does a Docker image build. Other builds will be added as separate PRs.

**Comment by erimatnor** [comment]
I am not sure integrating the official Dockerfile with our TimescaleDB repo is the right approach. The convention for Docker is to have a separate repository with the Dockerfile. The vast majority of Docker images are built from repos that only contain the Dockerfiles (see e.g., official list of database images: https://hub.docker.com/search?q=&type=image&category=database). Since the Docker image is often built from published artifacts (e.g., debs, rpms, tar ball, etc.) that are pulled from artifact repos (e.g., debs from packagecloud) and not from the output of a local build, it seldom makes sense to keep the Dockerfile bundled with the code. The exception might be experimental builds that aren't based on a release, but that can be done from a separate Dockerfile or a script (like the one we already have).

Look at, e.g., the InfluxDB docker image maintained by InfluxData. It has the "official" tag and a separate repo for building Docker images, as do most (if not all) other databases: 

https://hub.docker.com/_/influxdb
https://github.com/influxdata/influxdata-docker/

I think we should strive to achieve "official" status for our images, as most other well-known databases have already. And, I don't think that will be possible if we co-locate the Dockerfiles with our code in one monolothic repo.

**Comment by erimatnor** [comment]
About official images (something I think we should strive for): https://docs.docker.com/docker-hub/official_images/

**Comment by mkindahl** [comment]
> I am not sure integrating the official Dockerfile with our TimescaleDB repo is the right approach. The convention for Docker is to have a separate repository with the Dockerfile. The vast majority of Docker images are built from repos that only contain the Dockerfiles (see e.g., official list of database images: https://hub.docker.com/search?q=&type=image&category=database).

The convention for Docker is to keep the `Dockerfile` with the code that is being built (see https://docs.docker.com/docker-hub/builds/#set-up-build-rules, for example, where the default is to use the `Dockerfile` in the root of the source repository). The only reason that there are separate repositories with official images mentioned above is because those are build by Docker and not by the organization that builds the solution in question.

The recommended practice is to build all artifacts from the repository (see https://12factor.net/ for example.) This is also how it is done at Google (http://google-engtools.blogspot.com/2011/08/build-in-cloud-how-build-system-works.html) and this is also how Bazel is designed (https://docs.bazel.build/versions/4.1.0/build-ref.html), which is based on the build system that Google uses. This is also how most other applications are structured. See the following list for some examples of guides (mostly web applications, but the same apply here as well):

- https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
- https://blog.logrocket.com/packaging-a-rust-web-service-using-docker/
- https://dev.to/rogertorres/first-steps-with-docker-rust-30oi
- https://github.com/timescale/timescaledb-toolkit

This list above is specific to official images published by Docker for tools that are not build by Docker so I think this is a misrepresentation to say that it is a "vast majority". These are images build by Docker and are there because they cannot add `Dockerfiles` to the things they build.

> Since the Docker image is often built from published artifacts (e.g., debs, rpms, tar ball, etc.) that are pulled from artifact repos (e.g., debs from packagecloud) and not from the output of a local build, it seldom makes sense to keep the Dockerfile bundled with the code.

Our Dockerfiles do not build from RPMs or Debian packages, they build from source directly.

> The exception might be experimental builds that aren't based on a release, but that can be done from a separate Dockerfile or a script (like the one we already have).
> 
> Look at, e.g., the InfluxDB docker image maintained by InfluxData. It has the "official" tag and a separate repo for building Docker images, as do most (if not all) other databases:
> 
> https://hub.docker.com/_/influxdb
> https://github.com/influxdata/influxdata-docker/
> 
> I think we should strive to achieve "official" status for our images, as most other well-known databases have already. And, I don't think that will be possible if we co-locate the Dockerfiles with our code in one monolothic repo.

Placing build manifests (like CMake's `CMakeLists.txt`, or Bazel's `BUILD`, which is similar in function to `Dockerfiles`) does not make a repository monolithic. If it makes it monolithic, why do we not place the `CMakeLists.txt` in a separate repository?

> It should be possible to build a release pipeline that involves multiple repos without putting everything in one repository.

This is code, anything is possible, but that does not necessarily make it a good idea.

There are several advantages to keeping the `Dockerfile` in the same repository:

1. If dependencies need to be updated, all the files that require changes are in the same repository so they can be covered by a single pull request. No need to submit several different requests to different repositories to make such changes, or risk missing to update a dependency. This simplifies development greatly and avoid a lot of potential sources of errors.
2. Easy to find and understand all the necessary dependencies for the repository. No "hidden" repositories or odd dependencies because a separate repository was not updated properly.
3. Easy to add CI for each pull request that tests that all build manifests can be used. We previously had problems with dependencies being broken as a result of dependencies being in separate repositories and only ran as nightly build, which caused  caused significant frustration with developers. If artifacts for the repository is test-build on each pull request, problems in the repository will surface immediately and not later. This will simplify development significantly and eliminate a lot of frustration since there is no longer any need to chase down odd failures in nightly builds, nor miss to update some dependency in an unknown repository.
4. The build manifests are maintained at the same level as the repository source code. If all the build manifests are are in the same repository as the source code, they will be maintained at the same level as the source code itself since all is visible and CI will make sure that it works.

I don't see any advantages of keeping the `Dockerfile` out of the repository, buy it is necessary (even if not desirable) when you need to build images for something that you do not have control over.

**Review by afiskon — APPROVED** [review]

**Review by svenklemm — CHANGES_REQUESTED** [review]
We decided previously that we do not want these files in the main repository. The current docker workflows also build bitnami images and have multi-arch support which seems to be missing in this PR.

**Comment by erimatnor** [comment]
> The convention for Docker is to keep the `Dockerfile` with the code that is being built (see https://docs.docker.com/docker-hub/builds/#set-up-build-rules, for example, where the default is to use the `Dockerfile` in the root of the source repository). The only reason that there are separate repositories with official images mentioned above is because those are build by Docker and not by the organization that builds the solution in question.
> 

I was referring to official Docker images and my point is that we should aim for becoming an official image. Official images need not be maintained by Docker. For instance, InfluxDB is an "offical" image maintained by InfluxData (follow this link and look under "Quick reference" to see who is the maintaner: https://hub.docker.com/_/influxdb). Moving in the direction of bundling every Dockerfile in the main repo I believe will prevent us from making our own image "official", if that is what we want to do. This is my main concern.

I do realize that there are some advantages to keeping the Dockerfiles in the same repo as the source code, but I am not convinced those outweigh the downsides.

**Comment by mkindahl** [comment]
> We decided previously that we do not want these files in the main repository.

In light of the above comments, I am not sure why the decision was done in this way.

> The current docker workflows also build bitnami images and have multi-arch support which seems to be missing in this PR.

I added multi-arch support (one line added, so simple). Adding bitnami support means moving the second `Dockerfile` here, since it is not based on the alpine image, but that is easily added if that is all that is required.

**Comment by mkindahl** [comment]
> > The convention for Docker is to keep the `Dockerfile` with the code that is being built (see https://docs.docker.com/docker-hub/builds/#set-up-build-rules, for example, where the default is to use the `Dockerfile` in the root of the source repository). The only reason that there are separate repositories with official images mentioned above is because those are build by Docker and not by the organization that builds the solution in question.
> 
> I was referring to official Docker images and my point is that we should aim for becoming an official image. Official images need not be maintained by Docker. For instance, InfluxDB is an "offical" image maintained by InfluxData (follow this link and look under "Quick reference" to see who is the maintaner: https://hub.docker.com/_/influxdb). Moving in the direction of bundling every Dockerfile in the main repo I believe will prevent us from making our own image "official", if that is what we want to do. This is my main concern.

Looking at the Dockerfiles for the official images, they are completely different compared to what we have and if we want to create official images I think that we need something completely different from what we have now. In particular, these points are valid here:

1. The Dockerfiles of the official images install the corresponding package (e.g., the RPM or Debian package). Our Dockerfile build from source so this is completely different.
2. All the official images have a repository with a dedicated `Dockerfile` for each released version, which would mean that we would probably have to create something similar. They are basically mirroring the branch structure of the Git repository to be able to support all released versions.

In short: the official docker images are something completely different from what we have in the `timescaledb-docker` repository so it is not something we can or should use to create our official images.

> I do realize that there are some advantages to keeping the Dockerfiles in the same repo as the source code, but I am not convinced those outweigh the downsides.

Downsides mentioned this far:

- _We cannot update the Dockerfile between releases if we need to._ Even though this is true, it is a problem in practice. Looking at the log for `timescaledb-docker` I do not see a "real" update of the `Dockerfiles` in more than a year, so this is a only an academic problem, not an actual one. There are a few other more recent changes though, worth to mention:
  - There are updates of the version in the `Dockerfile`, which is not needed here because the version is automatically retrieved from the `version.config` file and passed as a parameter to the `Dockerfile`.
  - There are updates to disable TAP tests, which would not have been necessary at all since that would have been caught and fixed if the `Dockerfile` was part of the repository.
- _We cannot use the `Dockerfile` to create an official image._ Since the official images are build in a completely different way and have a completely different structure, we cannot use the current Dockerfiles anyway and need to create something new.
- _It is not the convention to place the Dockerfile with the repository._  This is actually not correct. Most guides and recommendations quoted above recommend this. Many out-of-source builds of docker images do use this approach, but not because it is better, only because there is no alternative.

In summary, there are several advantages listed in previous comment that would make development significantly easier and less error-prone, but I have this far not seen anything that can be considered a downside, except from an academic perspective.

**Comment by mkindahl** [comment]
> > The current docker workflows also build bitnami images and have multi-arch support which seems to be missing in this PR.
> 
> I added multi-arch support (one line added, so simple). Adding bitnami support means moving the second `Dockerfile` here, since it is not based on the alpine image, but that is easily added if that is all that is required.

I added bitnami support to the PR by moving and adapting the bitnami Dockerfile.

**Pull request closed without merging**
