### PR TITLE
Eliminate typedef redeclarations

### LINKED ISSUE #37: Build fails on older OS (e.g., CentOS 6.8), older versions of gcc
Hi,
    gcc version:4.4.7

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -fpic -DINCLUDE_PACKAGE_SUPPORT=0 -MMD -I. -I./ -I/usr/local/postgresql-9.6.2/include/server -I/usr/local/postgresql-9.6.2/include/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/metadata_queries.o src/metadata_queries.c
In file included from src/metadata_queries.c:14:
src/chunk.h:23: error: redefinition of typedef ‘Chunk’
src/metadata_queries.h:6: note: previous declaration of ‘Chunk’ was here
make: *** [src/metadata_queries.o] Error 1

### PR DESCRIPTION
**Pull request by medranocalvo**
Place typedefs before local includes in order for the alias types to be
declared even in the case of with mutual dependencies between header
files.

Fixes #37 for GCC 4.3.

This is a trivial change.

### CODE REVIEW

**Comment by RobAtticus** [comment]
Hey @medranocalvo , thanks for submitting this PR. I am worried however that these changes make the codebase messier to read and the benefit only seems to be to support gcc 4.3, a nearly 10-year old compiler. Are you using a platform where that is the only thing available?

**Comment by medranocalvo** [comment]
Yes, SLES11 in our case.

The rule is simple: _in *.h files place the typedefs before the local includes_.  The difficult thing is getting used to following it, especially when the platform you use is not impacted (needs `-Wpedantic`, AFAICS).  This change suffices to build timescaledb cleanly on old, but supported, platforms.

**Comment by RobAtticus** [comment]
Interesting. It does not appear that PostgreSQL supports 9.6 or 10 on SLES11? Are you using an unofficial port? Discussion among our team has had people pushback about doing this change, so I think we might not do this. Also I cannot merge without a signed CLA.

**Comment by RobAtticus** [comment]
I am going to close this for now, happy to discuss it further however.

**Comment by RobAtticus** [comment]
And of course we appreciate the effort even though it's unlikely we will merge.

**Comment by kanazir** [comment]
> Hey @medranocalvo , thanks for submitting this PR. I am worried however that these changes make the codebase messier to read and the benefit only seems to be to support gcc 4.3, a nearly 10-year old compiler. Are you using a platform where that is the only thing available?

Well, I tried with gcc 4.4.7, 5.5.0 and 8.3.0 and compilation fails every time for the same reason. Which gcc version to use if I don't want to modify the source?

**Pull request closed without merging**
