### PR TITLE
Fix gitcommit regenerate issue

### LINKED ISSUE #4490: [Bug]: gitcommit.h not reliably regenerated
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Build system

### What happened?

gitcommit.h does not get reliably rebuilt on git commit hash change

### TimescaleDB version affected

main

### PostgreSQL version used

14.4

### What operating system did you use?

Archlinux 2022.07.01 x64

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
postgres@db1[1452199]=# SELECT * from _timescaledb_internal.get_git_commit();
         commit_tag         | commit_hash |      commit_time
----------------------------+-------------+------------------------
 2.0.0-beta6-853-g37190e8a8 | 0f7ab056c   | 2022-02-21 11:35:27+01
(1 row)
```

```
 sven  alice    ~/projects/timescaledb/build_pg14  ⚓ 37190e8a8  76+  %  cat src/gitcommit.h
/*
 * This file and its contents are licensed under the Apache License 2.0.
 * Please see the included NOTICE for copyright information and
 * LICENSE-APACHE for a copy of the license.
 */

#ifndef GITCOMMIT_H_
#define GITCOMMIT_H_

#define EXT_GIT_COMMIT_TAG "2.0.0-beta6-852-g0f7ab056c"
#define EXT_GIT_COMMIT_HASH "0f7ab056c"
#define EXT_GIT_COMMIT_TIME "2022-02-21T11:23:12+03:00"

#endif /* GITCOMMIT_H_ */
```

### How can we reproduce the bug?

```bash
cd BUILD_DIR
git checkout 0f7ab056c
make
cat src/gitcommit.h
git checkout 37190e8a8
make
cat src/gitcommit.h
```

### PR DESCRIPTION
**Pull request by RafiaSabih**
Create gitcommit.h everytime the commit info is changed.

Fixes #4490

### CODE REVIEW

**Comment by fabriziomello** [comment]
Not sure what's this PR is supposed to fix, after build it and compare against `main` seems that anything changed:

1. first I checked in your branch:

```bash
timescaledb on  gitcommit_fix [$] 
➜ cat ./build/src/gitcommit.h                     
/*
 * This file and its contents are licensed under the Apache License 2.0.
 * Please see the included NOTICE for copyright information and
 * LICENSE-APACHE for a copy of the license.
 */

#ifndef GITCOMMIT_H_
#define GITCOMMIT_H_

#define EXT_GIT_COMMIT_TAG "2.0.0-beta6-1082-g15abd8a9"
#define EXT_GIT_COMMIT_HASH "15abd8a9"
#define EXT_GIT_COMMIT_TIME "2022-07-21T19:49:51+02:00"

#endif /* GITCOMMIT_H_ */

timescaledb on  gitcommit_fix [$] 
➜ git logline | head -n 1   
* 15abd8a9 - (HEAD -> gitcommit_fix) Fix gitcommit regenerate issue (66 minutes ago) <Rafia Sabih>
```

2. then I checked the `main` branch:

```bash
timescaledb on  main [$] took 5s 
➜ cat ./build/src/gitcommit.h
/*
 * This file and its contents are licensed under the Apache License 2.0.
 * Please see the included NOTICE for copyright information and
 * LICENSE-APACHE for a copy of the license.
 */

#ifndef GITCOMMIT_H_
#define GITCOMMIT_H_

#define EXT_GIT_COMMIT_TAG "2.0.0-beta6-1080-g296601b1"
#define EXT_GIT_COMMIT_HASH "296601b1"
#define EXT_GIT_COMMIT_TIME "2022-07-21T18:24:59+05:30"

#endif /* GITCOMMIT_H_ */

timescaledb on  main [$] 
➜ git logline | head -n 1    
* 296601b1 - (HEAD -> main, upstream/main, origin/main, origin/HEAD) Synchronize chunk cache sizes (6 hours ago) <Alexander Kuzmenkov>
```

I mean ... tried it in different branches and *seems* it was generating it properly, am I missing something?

**Comment by svenklemm** [comment]
https://github.com/timescale/timescaledb/issues/4490 is the ticket describing the issue which includes reproduction steps.

**Comment by mfundul** [comment]
In my testing it's not really working. Maybe try something like this? https://stackoverflow.com/questions/3780667/use-cmake-to-get-build-time-subversion-revision

**Comment by mfundul** [comment]
My assumption is that we want `make` to generate this, without explicitly having to run `cmake` again.

**Comment by svenklemm** [comment]
Seems like the gitcommit.h is not always regenerated when running make. I changed a C-file so the tree-state is dirty:
```
git describe --dirty
2.0.0-beta6-1087-gffc5a7e2a-dirty
```
But the EXT_GIT_COMMIT_TAG in the header file is not updated after running make. Not even after running make clean and make does the header file have the correct information. Only after running bootstrap again does the header file have the dirty-flag

**Review by svenklemm — APPROVED** [review]

**Pull request merged**
