### PR TITLE
change planner cost for (merge)append nodes

### PR DESCRIPTION
**Pull request by fvannee**
We have been noticing poor planner choices in a large part of our queries in cases where we have a large number of chunks. After some investigation we found out it has to do with the planner estimations of the Append and MergeAppend nodes. Specifically, the MergeAppend node calculates its cost by adding the cost of its subnodes together and adding some factor on top of it for merging.
In our use cases we always have explicit WHERE clauses to prune all except one chunk. However, since calculating of the cost is done before pruning, these nodes report much higher cost than they actually have.
Somehow, this leads the planner to disgregard Index Scan on remaining chunk -> Merge Append (on just one stream) and prefer a Sequential Scan on chunk -> Append -> Sort. This is way slower than the MergeAppend plan. Furthermore, it is practically impossible to force the Postgres planner to use Index scans and/or MergeAppend other than setting enable_sort to false (even changing the standard Postgres planning cost parameters did not make a difference in our tests).
In my opinion it makes more sense to assume in the cost calculation that a large part of the (Merge)Append nodes can be pruned away. Attached PR changes the cost calculation to essentially assume that just one chunk needs to be scanned and leads to much more efficient plans for the queries that we have tested it with.
Please note that I understand this PR might have drawbacks for use cases where none or only a small number of chunks can be pruned, but I believe it makes more sense to assume that a large part can be pruned, rather than assuming nothing can be pruned.
This PR is meant as a starting point for a discussion what would be a good choice here. I would like to see that the cost is lowered to make the MergeAppend node more likely to be chosen and I'd like to hear your feedback on this.

### CODE REVIEW

**Comment by fvannee** [comment]
Any opinions or feedback on this change?

**Comment by cevian** [comment]
Hi @fvannee, I was waiting to finish #502 before giving this a thorough review because I think they are related (since #502) does punning earlier in the planning process. I'd like to test this problem some more on top of that branch. Can you provide a test case where the planner (before this change) messes up?

**Comment by fvannee** [comment]
I believe the currently failing unit tests of the append.sql file illustrate the difference nicely. I don't think you'd see a definite difference in performance when executing the queries in the unit tests though, as the data in the tables is very small. However, the planner will choose the same plan with large amounts of data in tables, leading to a large unnecessary sorting time. In my opinion merge append is in most cases a better plan.
For examples, see: https://api.travis-ci.org/v3/job/367353897/log.txt
Eg.
```
!                                                              QUERY PLAN                                                             
! ------------------------------------------------------------------------------------------------------------------------------------
!  Sort
!    Sort Key: append_test."time"
!    ->  Custom Scan (ConstraintAwareAppend)
!          Hypertable: append_test
!          Chunks left after exclusion: 1
!          ->  Append
!                ->  Bitmap Heap Scan on _hyper_1_3_chunk
!                      Recheck Cond: ("time" > ('Tue Aug 22 10:00:00 2017 PDT'::timestamp with time zone - '@ 2 mons'::interval))
!                      ->  Bitmap Index Scan on _hyper_1_3_chunk_append_test_time_idx
!                            Index Cond: ("time" > ('Tue Aug 22 10:00:00 2017 PDT'::timestamp with time zone - '@ 2 mons'::interval))
! (10 rows)
  
  -- currently, we cannot distinguish between stable and volatile
  -- functions as far as applying our modified plan. However, volatile
--- 160,175 ----
  ORDER BY time;
  psql:include/append.sql:75: NOTICE:  Immutable function now_i() called!
  psql:include/append.sql:75: NOTICE:  Immutable function now_i() called!
!                                                        QUERY PLAN                                                       
! ------------------------------------------------------------------------------------------------------------------------
!  Custom Scan (ConstraintAwareAppend)
!    Hypertable: append_test
!    Chunks left after exclusion: 1
!    ->  Merge Append
!          Sort Key: _hyper_1_3_chunk."time"
!          ->  Index Scan Backward using _hyper_1_3_chunk_append_test_time_idx on _hyper_1_3_chunk
!                Index Cond: ("time" > ('Tue Aug 22 10:00:00 2017 PDT'::timestamp with time zone - '@ 2 mons'::interval))
! (7 rows)
```

**Comment by cevian** [comment]
We'd like to understand more thoroughly why a mergeappend is less desirable with many chunks according to the planner? Do you have any insight into that? We are a bit hesitant on making these kind of assumptions in the query plan before understanding more thoroughly what's going on.

**Comment by fvannee** [comment]
Consider a hypertable which stores sensor (id, value) pairs together with some updated_at timestamp. A typical query which queries the last update of a certain sensor:

SELECT DISTINCT ON (sensor_id), * FROM table WHERE sensor_id=2 AND updated_at BETWEEN now() - interval '1 day' AND now() ORDER BY sensor_id, updated_at DESC

At planning time, the planner can choose between doing (inner to outer)
Index Scan on chunk(s) -> Append -> Sort -> Limit
Or
Index Scan on chunk(s) -> Merge Append -> Limit

However, the planner doesn't know at planning time (when it determines the cost) how many chunks it can prune. Currently it assumes no chunks can be pruned at all, which seems quite unlikely in the case of hypertables. If no chunks can be pruned at all, it means the planner thinks it needs to do a Merge Append on many chunks, which is obviously very expensive as the cost estimation of the MergeAppend node depends heavily (N*log N I believe?) on the number of chunks it needs to merge together. The Append node has no such overhead. Therefore the planner prefers Append over Merge Append when nothing can be pruned.

By the time pruning takes place and we know that in fact we only have one chunk to scan instead of the 100+ chunks we are already constructing the plan so we're basically too late to change anything about the Append vs Merge Append then.

**Comment by cevian** [comment]
Is MergeAppend overhead really N log N? If so that seems wrong MergeAppend overhead should be minimal. Also in the Append case the Sort should be way more expensive than any MergeAppend overhead. I am not quite sure why it isn't.

**Comment by fvannee** [comment]
Planner cost calculation of Merge Append node is defined here: https://github.com/postgres/postgres/blob/9a994e37e08df3578f52011543dc28085dc18e21/src/backend/optimizer/path/costsize.c#L1957
There's some N*log N startup cost to create the initial heap and then log N*num_tuples cost for the execution itself. I am also not 100% sure why the planner underestimates sorting cost by so much, but in no way I have been able to tune parameters to affect just sorting and not the Merge Append (because they use the same underlying parameters to determine the cost..)

**Comment by cevian** [comment]
So I did some digging. In the examples from the log that you pointed out above, the actual root cause is that the `Bitmap Heap Scan` is costed out much cheaper than `Index Scan Backward` and that's because of the setting of `random_page_cost`. Once I set the default for `random_page_cost` lower than the default of 4 (which is in any case a very bad setting for modern SSD disks) the plan switched to the MergeAppend (I set it to 1, I know many people set it even lower). Another thing that helps the cost function is putting in a LIMIT clause (even if it's a giant overestimate for the total you expect it helps the planner figure out that less tuples than the total in the table will be processed).  Can you try and see if any of that works for your queries?

**Comment by cevian** [comment]
@fvannee any feedback about my comment above. Can I close this?

**Comment by cevian** [comment]
@fvannee closing this for now since afaik the approaches I listed above work AFAIK. Feel free to reopen/ping me if you disagree.

**Pull request closed without merging**
