### PR TITLE
Fix refresh window cap for cagg refresh

### LINKED ISSUE #4252: [Bug]: Refresh policy for continuous aggregate causes more data to materialize for another continuous aggregate
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Policy

### What happened?

Originally posted by @Vinay-Raghu 

We have 2 continuous aggregates:
```
1. deals_best_weekly
2. deals_best_daily
```
both with refresh policies like this: 
start_offset => interval '15 days',
end_offset => interval '1 day',
schedule_interval => interval '1 day');

The problem is that it seems like cagg_daily refresh policy is somehow causing data in the current time bucket for deals_best_weekly continuous aggregate to materialize.

To recreate: 

First create the table and insert some data:
```
-- Step 1: Create the table
CREATE TABLE IF NOT EXISTS sensor_data(
time TIMESTAMPTZ NOT NULL,
sensor_id INTEGER,
temperature DOUBLE PRECISION,
cpu DOUBLE PRECISION);

-- Step 2: Create hypertable
SELECT create_hypertable('sensor_data','time');

-- Step 3: Insert the data
INSERT INTO sensor_data(time, sensor_id, cpu, temperature)
SELECT 
time,
sensor_id,
round((random() * (100-0) + 0) :: NUMERIC,4) AS cpu,
floor(random() * (83-20) + 28) AS temperature
FROM 
generate_series(now() - interval '3 months', now(), interval '10 minutes') as g1(time),
generate_series(1,1000,1) as g2(sensor_id);
```

Then create the continuous aggregates and turn off real time aggregation: 
```
-- Step 4: Create the caggs
create materialized view deals_best_weekly
with (timescaledb.continuous) AS
SELECT 
time_bucket('7 days', "time") AS bucket, 
min(temperature) AS min_temp, 
max(cpu) AS max_rating 
FROM sensor_data 
GROUP by bucket
with no data;

create materialized view deals_best_daily
with (timescaledb.continuous) AS
SELECT 
time_bucket('1 day', "time") AS bucket, 
min(temperature) AS min_temp, 
max(cpu) AS max_rating 
FROM sensor_data 
GROUP by bucket
with no data;

-- Step 5: Turn off real-time agg
alter materialized view deals_best_weekly set (timescaledb.materialized_only=true);
alter materialized view deals_best_daily set (timescaledb.materialized_only=true);
```
Create the policy for the weekly aggregate: 
```
SELECT add_continuous_aggregate_policy('deals_best_weekly',
start_offset => interval '15 days',
end_offset => interval '1 day',
schedule_interval => interval '1 minute');
```
It will run almost immediately giving the following: 
```
select * from deals_best_weekly ;
         bucket         | min_temp | max_rating 
------------------------+----------+------------
 2022-04-11 02:00:00+02 |       28 |    99.9999
(1 row)
``` 
Then add the policy for the daily aggregate:`
```
select add_continuous_aggregate_policy('deals_best_daily',
start_offset => interval '15 days',
end_offset => interval '1 day',
schedule_interval => interval '1 minute');
```
That will also run immediately:
```
select * from deals_best_daily ;
         bucket         | min_temp | max_rating 
------------------------+----------+------------
 2022-04-18 02:00:00+02 |       28 |    99.9993
 2022-04-09 02:00:00+02 |       28 |    99.9999
 2022-04-14 02:00:00+02 |       28 |    99.9997
 2022-04-08 02:00:00+02 |       28 |        100
 2022-04-17 02:00:00+02 |       28 |    99.9997
 2022-04-11 02:00:00+02 |       28 |    99.9998
 2022-04-06 02:00:00+02 |       28 |    99.9996
 2022-04-12 02:00:00+02 |       28 |    99.9993
 2022-04-07 02:00:00+02 |       28 |    99.9993
 2022-04-13 02:00:00+02 |       28 |    99.9999
 2022-04-16 02:00:00+02 |       28 |    99.9994
 2022-04-15 02:00:00+02 |       28 |    99.9999
 2022-04-10 02:00:00+02 |       28 |    99.9997
(13 rows)
```
But, when the weekly policy is executed again, after adding the daily policy, we see one more materialized bucket: 
```
select * from deals_best_weekly ;
         bucket         | min_temp | max_rating 
------------------------+----------+------------
 2022-04-18 02:00:00+02 |       28 |    99.9999
 2022-04-11 02:00:00+02 |       28 |    99.9999
(2 rows)
```

### TimescaleDB version affected

2.6.0

### PostgreSQL version used

12.9

### What operating system did you use?

MacOS Monterey 12.2.1 M1

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

_No response_

### PR DESCRIPTION
**Pull request by konskov**
Fixes #4252

### CODE REVIEW

**Review by akuzm — APPROVED** [review]
Ohh that's nasty! I have a personal rule about this: if I have two objects of some type, both of them must have some modifier, there shouldn't be "just" the object because it leads to similar typos. E.g. here I'd use something 'requested_refresh_window' and 'actual_refresh_window'. I don't mean you should change the names now, just saying.

**Review by mfundul — APPROVED** [review]
Nice catch @konskov !

**Review by mfundul — CHANGES_REQUESTED** [review]
Ah, you should add the corresponding test case.

**Review by mfundul — APPROVED** [review]
Did you run this test case without the code fix and it always failed?

**Comment by konskov** [comment]
I ran it a couple of times to check, the result I got is this:
```
+-- we have data from 6 weeks before to May 5 2022 (Thu)
+CALL refresh_continuous_aggregate('deals_best_weekly', '2022-04-24', '2022-05-03');
+SELECT * FROM deals_best_weekly;
+            bucket            |     avg_temp     | max_rating 
+------------------------------+------------------+------------
+ Sun Apr 24 17:00:00 2022 PDT | 117.764705882353 |          6
+(1 row)
+
+CALL refresh_continuous_aggregate('deals_best_daily', '2022-04-20', '2022-05-04');
+SELECT * FROM deals_best_daily ORDER BY bucket LIMIT 2;
+            bucket            | avg_temp | max_rating 
+------------------------------+----------+------------
+ Wed Apr 20 17:00:00 2022 PDT |    110.8 |          4
+ Thu Apr 21 17:00:00 2022 PDT |   111.75 |          5
+(2 rows)
+
+-- expect to get an up-to-date notice
+CALL refresh_continuous_aggregate('deals_best_weekly', '2022-04-24', '2022-05-05');
+SELECT * FROM deals_best_weekly;
+            bucket            |     avg_temp     | max_rating 
+------------------------------+------------------+------------
+ Sun May 01 17:00:00 2022 PDT | 122.714285714286 |          3
+ Sun Apr 24 17:00:00 2022 PDT | 117.764705882353 |          6
+(2 rows)

**Pull request merged**
