### PR TITLE
Cherry-picked commits for RC4

### PR DESCRIPTION
**Pull request by mkindahl**
* Check configuration in alter_job and add_job
* Support gapfill on distributed hypertable
* Fix crash for concurrent drop and compress chunk
* Show more information in get_git_commit
* Fix timeout handling in async library
* Fix crash in add_job when given NULL interval
* Fix appveyor build
* Include user actions into job stats view
* Add hypertable to continuous aggregates view
* Fix support for complex aggregate expression
* Test latest PG 11.10 and 12.5

### CODE REVIEW

**Review by k-rus — COMMENTED** [review]
According to the plan 2 more PRs need to be completed and added to this RC.

**Comment by mkindahl** [comment]
> According to the plan 2 more PRs need to be completed and added to this RC.

Added the following PRs:

* Enabling release tests.
* Check configuration in alter_job and add_job

**Review by k-rus — COMMENTED** [review]
Instead of modifying actions the branch is usually force pushed into `prerelease_test`.
PR from Gayathri is still missing.

**Comment by mkindahl** [comment]
> Instead of modifying actions the branch is usually force pushed into `prerelease_test`.
I find this approach easier.

> PR from Gayathri is still missing.

Yup, waiting for that.

**Comment by k-rus** [comment]
> > Instead of modifying actions the branch is usually force pushed into `prerelease_test`.
> 
> I find this approach easier.

@mkindahl 
I am not sure it is good idea to keep this commit in the branch.

Will you cherry-pick your commit https://github.com/timescale/timescaledb/commit/d043ff1e041f22814f3d923860df85c84e99dbaf ? It is not important for the release, but good to have for completeness and to avoid divergence from the master branch.

**Comment by mkindahl** [comment]
> > > Instead of modifying actions the branch is usually force pushed into `prerelease_test`.
> > 
> > 
> > I find this approach easier.
> 
> @mkindahl
> I am not sure it is good idea to keep this commit in the branch.
> 
> Will you cherry-pick your commit ~[d043ff1](https://github.com/timescale/timescaledb/commit/d043ff1e041f22814f3d923860df85c84e99dbaf)~ [3544e33](https://github.com/timescale/timescaledb/commit/3544e33fb4d08105f587f87069299229b3a597ba) ? It is not important for the release, but good to have for completeness and to avoid divergence from the master branch.

I cherry-picked it into the branch.

**Comment by k-rus** [comment]
> > > Instead of modifying actions the branch is usually force pushed into `prerelease_test`.
> > 
> > 
> > I find this approach easier.
> 
> @mkindahl
> I am not sure it is good idea to keep this commit in the branch.

@mkindahl Am I correct that this commit, which removes `prerelease_test` from GH actions, was removed?

**Review by k-rus — APPROVED** [review]
I guess that the failed test is just a flaky one.

**Comment by mkindahl** [comment]
> > > > Instead of modifying actions the branch is usually force pushed into `prerelease_test`.
> > > 
> > > 
> > > I find this approach easier.
> > 
> > 
> > @mkindahl
> > I am not sure it is good idea to keep this commit in the branch.
> 
> @mkindahl Am I correct that this commit, which removes `prerelease_test` from GH actions, was removed?

@k-rus Yes, it was removed

**Comment by mkindahl** [comment]
> I guess that the failed test is just a flaky one.

There are several flaky ones, I'm rerunning them as I discover them. The last one was about a missing Webhook for Slack.

**Review by svenklemm — APPROVED** [review]

**Review by pmwkaa — APPROVED** [review]

**Comment by k-rus** [comment]
> There are several flaky ones, I'm rerunning them as I discover them. The last one was about a missing Webhook for Slack

@mkindahl 
Webhook error only happens when there was an error before, since it tries to report the error. I noticed one failed test during installcheck, but I think it's flaky one.

**Comment by svenklemm** [comment]
> > There are several flaky ones, I'm rerunning them as I discover them. The last one was about a missing Webhook for Slack
> 
> @mkindahl
> Webhook error only happens when there was an error before, since it tries to report the error. I noticed one failed test during installcheck, but I think it's flaky one.

Webhook doesnt work in PRs cause you dont have access to github secrets in PRs but its only triggered by previous errors so those should be investigated

**Pull request merged**
