### PR TITLE
Fix timestamp test

### PR DESCRIPTION
**Pull request by erimatnor**
The timestamp test broke with Postgres 9.6.3, because that version
contained an accuracy fix for the `to_timestamp()` function, giving
slightly different results for some timestamp values. This fixes the
timestamp test to expect the correct `to_timestamp()` output as of
version 9.6.3 of Postgres.

### CODE REVIEW

**Comment by erimatnor** [comment]
Note that this effectively bumps the required version of Postgres to v9.6.3, at least as far as tests are concerned.

**Comment by cevian** [comment]
Shouldn't we just truncate the result so the regression test works on both versions? Or am I missing something?

**Comment by erimatnor** [comment]
What would be the point of the test if we truncate the result? The test is supposed to show that our own time-converting function gives the same output as the `to_timestamp()` one in PostgreSQL, which it didn't do before because of a regression in official PostgreSQL (now fixed in 9.6.3).

**Comment by RobAtticus** [comment]
You'll have to update the Dockerfile base image to be 9.6.3 then, since travis uses the docker to test. Otherwise the CI check won't work anymore.

**Comment by erimatnor** [comment]
Updated to v9.6.3, all checks now pass.

**Pull request merged**
