### PR TITLE
PG16 - Adapt to the new RTEPerminfo logic.

### PR DESCRIPTION
**Pull request by lkshminarayanan**
With the two commits included in this PR, timescaledb can be compiled with PG16.

Disable-check: force-changelog-file
Disable-check: commit-count

### CODE REVIEW

**Comment by lkshminarayanan** [comment]
Couple more PG16 patches in https://github.com/lkshminarayanan/timescaledb/commits/pg16-fixes if anyone is interested.

**Review by fabriziomello — APPROVED** [review]

**Review by akuzm — APPROVED** [review]

**Comment by fabriziomello** [comment]
> Couple more PG16 patches in https://github.com/lkshminarayanan/timescaledb/commits/pg16-fixes if anyone is interested.

Thanks a lot @lkshminarayanan ... we'll take care of it and add you as author

**Comment by lkshminarayanan** [comment]
> > Couple more PG16 patches in https://github.com/lkshminarayanan/timescaledb/commits/pg16-fixes if anyone is interested.
> 
> Thanks a lot @lkshminarayanan ... we'll take care of it and add you as author

Sure! Thank you @fabriziomello.

**Review by fabriziomello — APPROVED** [review]

**Comment by fabriziomello** [comment]
Merged it and will send a following PR with some fixes on regression tests suite.

**Pull request merged**
