### PR TITLE
Fix flaky issues test

### PR DESCRIPTION
**Pull request by svenklemm**
Change the distributed insert test to shared test so it can run in
parallel and doesn't require dedicated distributed setup.

### CODE REVIEW

**Review by mkindahl — APPROVED** [review]

**Review by pmwkaa — APPROVED** [review]
How moving this test helps not being flaky, does it conflict with others?

**Comment by svenklemm** [comment]
> How moving this test helps not being flaky, does it conflict with others?

The flakyness was due to non-unique datanode names, which using shared test circumvents

**Comment by pmwkaa** [comment]
> datanode

If it is related to conflicting database names @mkindahl is working on PR to make them separate based on test name. Maybe it should be fixed that way instead?

**Comment by svenklemm** [comment]
> > datanode
> 
> If it is related to conflicting database names @mkindahl is working on PR to make them separate based on test name. Maybe it should be fixed that way instead?

Thats for a different test, and in general tests should preferably run as shared test as there is less overhead involved in those leading to faster test execution.

**Pull request merged**
