### PR TITLE
Fix some of the least controversial clang-tidy warnings

### PR DESCRIPTION
**Pull request by akuzm**
Cosmetic stuff mostly.

Disable-check: commit-count

### CODE REVIEW

**Review by mkindahl — APPROVED** [review]
LGTM. Assume these were changes that `clang-tidy` found and corrected itself?

**Comment by akuzm** [comment]
> LGTM. Assume these were changes that `clang-tidy` found and corrected itself?

Yep, I used the `--fix` option to make it fix them.

**Comment by svenklemm** [comment]
can you please push to prerelease_test and check it's all green for these changes

**Comment by svenklemm** [comment]
> > can you please push to prerelease_test and check it's all green for these changes
> 
> Pushed. Does it have some relevant additional checks?

Runs against broader variety of configurations.

**Review by svenklemm — APPROVED** [review]

**Pull request merged**
