### PR TITLE
Prepare the repo for next development cycle

### PR DESCRIPTION
**Pull request by RobAtticus**

### CODE REVIEW

**Comment by RobAtticus** [comment]
Please make sure I updated the appropriate places given the changes to the update process.

**Comment by erimatnor** [comment]
Ahh, it's the versioned output in the test. I guess we should fix that. Either we avoid displaying the version in the error (e.g., we can move it to errdetails), or we mute the error output in the test.

**Comment by erimatnor** [comment]
I suggest something like this for the error message:
```
	ereport(ERROR,
			(errcode(ERRCODE_DUPLICATE_OBJECT),
			 errmsg("the session already has another shared library loaded for extension \"%s\"", stmt->extname),
			 errdetail("The loaded version is \"%s\"", soversion),
			 errhint("You should start a new session and execute CREATE EXTENSION as the first command")));
```

**Comment by RobAtticus** [comment]
I like it, @cevian does that work for you?

**Comment by cevian** [comment]
@RobAtticus yup

**Pull request merged**
