### PR TITLE
Bump postgres versions used in CI

### PR DESCRIPTION
**Pull request by svenklemm**
Bump postgres versions used in CI to 14.3, 13.7 and 12.11.

Disable-check: commit-count

### CODE REVIEW

**Review by akuzm — APPROVED** [review]

**Review by fabriziomello — APPROVED** [review]

**Comment by fabriziomello** [comment]
@svenklemm wouldn't better send those refactoring in another PR??? Because we approved it based on the $SUBJECT and $DESCRIPTION

**Comment by svenklemm** [comment]
> @svenklemm wouldn't better send those refactorings in another PR??? Because we approved it based on the $SUBJECT and $DESCRIPTION

These are related to subject and will cut done the number of places we have to adjust when doing another bump for the next postgres version in a couple months. So I dont think we need separate PRs here.

**Comment by fabriziomello** [comment]
> > @svenklemm wouldn't better send those refactorings in another PR??? Because we approved it based on the $SUBJECT and $DESCRIPTION
> 
> These are related to subject and will cut done the number of places we have to adjust when doing another bump for the next postgres version in a couple months. So I dont think we need separate PRs here.

One idea for the future can be get the versions from here: https://www.postgresql.org/versions.rss

**Comment by svenklemm** [comment]
> > > @svenklemm wouldn't better send those refactorings in another PR??? Because we approved it based on the $SUBJECT and $DESCRIPTION
> > 
> > 
> > These are related to subject and will cut done the number of places we have to adjust when doing another bump for the next postgres version in a couple months. So I dont think we need separate PRs here.
> 
> One idea for the future can be get the versions from here: https://www.postgresql.org/versions.rss

Unfortunately release of a new postgres version does not mean it is packaged everywhere. Atm this PR is blocked because docker images for the new version are still not yet available after almost a week of tagging 14.3.

**Pull request merged**
