### PR TITLE
Fix recursion in cache processing

### LINKED ISSUE #2200: Segfault in cache code
**Relevant system information:**
 - OS: [e.g. Ubuntu 16.04, Windows 10 x64, etc]
 - PostgreSQL version (output of `postgres --version`): [e.g. 11.3, 12.0]
 - TimescaleDB version (output of `\dx` in `psql`): [e.g. 1.0.0]
 - Installation method: [e.g., "using Docker", "apt install", "source"]

**Describe the bug**
It generates a segfault.

**Additional context**

Stack dump:
```
Core was generated by `postgres: tfuxfphvz9-jk7n6bwl7d: autovacuum worker   tsdb                     '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055fd82fd836d in SearchCatCache (cache=0x55fd83ec2680, v1=140307775712714, v1@entry=35, v2=v2@entry=0, v3=v3@entry=0, v4=v4@entry=0) at ./build/../src/backend/utils/cache/catcache.c:1152
1152	./build/../src/backend/utils/cache/catcache.c: No such file or directory.
(gdb) bt
#0  0x000055fd82fd836d in SearchCatCache (cache=0x55fd83ec2680, v1=140307775712714, v1@entry=35, v2=v2@entry=0, v3=v3@entry=0, v4=v4@entry=0) at ./build/../src/backend/utils/cache/catcache.c:1152
#1  0x000055fd82fea291 in SearchSysCache (key4=0, key3=0, key2=0, key1=35, cacheId=<optimized out>) at ./build/../src/backend/utils/cache/syscache.c:1244
#2  GetSysCacheOid (cacheId=cacheId@entry=35, oidcol=oidcol@entry=1, key1=key1@entry=140307775712714, key2=key2@entry=0, key3=key3@entry=0, key4=key4@entry=0)
    at ./build/../src/backend/utils/cache/syscache.c:1244
#3  0x000055fd82c66227 in get_namespace_oid (nspname=nspname@entry=0x7f9bf3216dca "_timescaledb_cache", missing_ok=missing_ok@entry=true) at ./build/../src/backend/catalog/namespace.c:3039
#4  0x00007f9bf31f287b in proxy_table_exists () at /build/timescaledb/src/extension_utils.c:167
#5  extension_current_state () at /build/timescaledb/src/extension_utils.c:167
#6  0x00007f9bf31f3157 in extension_update_state () at /build/timescaledb/src/extension.c:270
#7  ts_extension_is_loaded () at /build/timescaledb/src/extension.c:270
#8  0x00007f9bf31dd299 in cache_invalidate_callback (arg=<optimized out>, relid=7560118) at /build/timescaledb/src/cache_invalidate.c:74
#9  0x000055fd82fda7a7 in LocalExecuteInvalidationMessage (msg=0x7fff28582160) at ./build/../src/backend/utils/cache/inval.c:595
#10 0x000055fd82ea597b in ReceiveSharedInvalidMessages (invalFunction=invalFunction@entry=0x55fd82fda6b0 <LocalExecuteInvalidationMessage>,
    resetFunction=resetFunction@entry=0x55fd82fd9ab0 <InvalidateSystemCaches>) at ./build/../src/backend/storage/ipc/sinval.c:90
#11 0x000055fd82fd9eb3 in AcceptInvalidationMessages () at ./build/../src/backend/utils/cache/inval.c:683
#12 0x000055fd82ea901a in LockRelationOid (relid=2615, lockmode=1) at ./build/../src/backend/storage/lmgr/lmgr.c:136
#13 0x000055fd82bc0055 in relation_open (relationId=2615, lockmode=lockmode@entry=1) at ./build/../src/backend/access/common/relation.c:56
#14 0x000055fd82c2935e in table_open (relationId=<optimized out>, lockmode=lockmode@entry=1) at ./build/../src/backend/access/table/table.c:43
#15 0x000055fd82fd7c4e in SearchCatCacheMiss (cache=cache@entry=0x55fd83ec2680, nkeys=nkeys@entry=1, hashValue=2512250167, hashIndex=3, v1=v1@entry=140307775712714, v2=v2@entry=0, v3=0, v4=0)
    at ./build/../src/backend/utils/cache/catcache.c:1357
#16 0x000055fd82fd8546 in SearchCatCacheInternal (v4=<optimized out>, v3=0, v2=0, v1=0, nkeys=<optimized out>, cache=0x55fd83ec2680) at ./build/../src/backend/utils/cache/catcache.c:1299
--Type <RET> for more, q to quit, c to continue without paging--
#17 SearchCatCache (cache=0x55fd83ec2680, v1=v1@entry=35, v2=v2@entry=0, v3=v3@entry=0, v4=v4@entry=0) at ./build/../src/backend/utils/cache/catcache.c:1153
#18 0x000055fd82fea291 in SearchSysCache (key4=0, key3=0, key2=0, key1=35, cacheId=<optimized out>) at ./build/../src/backend/utils/cache/syscache.c:1244
#19 GetSysCacheOid (cacheId=cacheId@entry=35, oidcol=oidcol@entry=1, key1=key1@entry=140307775712714, key2=key2@entry=0, key3=key3@entry=0, key4=key4@entry=0)
    at ./build/../src/backend/utils/cache/syscache.c:1244
#20 0x000055fd82c66227 in get_namespace_oid (nspname=nspname@entry=0x7f9bf3216dca "_timescaledb_cache", missing_ok=missing_ok@entry=true) at ./build/../src/backend/catalog/namespace.c:3039
#21 0x00007f9bf31f287b in proxy_table_exists () at /build/timescaledb/src/extension_utils.c:167
#22 extension_current_state () at /build/timescaledb/src/extension_utils.c:167
#23 0x00007f9bf31f3157 in extension_update_state () at /build/timescaledb/src/extension.c:270
#24 ts_extension_is_loaded () at /build/timescaledb/src/extension.c:270
#25 0x00007f9bf31dd299 in cache_invalidate_callback (arg=<optimized out>, relid=7560124) at /build/timescaledb/src/cache_invalidate.c:74
#26 0x000055fd82fda7a7 in LocalExecuteInvalidationMessage (msg=0x7fff28582590) at ./build/../src/backend/utils/cache/inval.c:595
#27 0x000055fd82ea597b in ReceiveSharedInvalidMessages (invalFunction=invalFunction@entry=0x55fd82fda6b0 <LocalExecuteInvalidationMessage>,
    resetFunction=resetFunction@entry=0x55fd82fd9ab0 <InvalidateSystemCaches>) at ./build/../src/backend/storage/ipc/sinval.c:90
#28 0x000055fd82fd9eb3 in AcceptInvalidationMessages () at ./build/../src/backend/utils/cache/inval.c:683
#29 0x000055fd82ea901a in LockRelationOid (relid=2615, lockmode=1) at ./build/../src/backend/storage/lmgr/lmgr.c:136
#30 0x000055fd82bc0055 in relation_open (relationId=2615, lockmode=lockmode@entry=1) at ./build/../src/backend/access/common/relation.c:56
#31 0x000055fd82c2935e in table_open (relationId=<optimized out>, lockmode=lockmode@entry=1) at ./build/../src/backend/access/table/table.c:43
#32 0x000055fd82fd7c4e in SearchCatCacheMiss (cache=cache@entry=0x55fd83ec2680, nkeys=nkeys@entry=1, hashValue=2512250167, hashIndex=3, v1=v1@entry=140307775712714, v2=v2@entry=0, v3=0, v4=0)
    at ./build/../src/backend/utils/cache/catcache.c:1357
```

### PR DESCRIPTION
**Pull request by cevian**
Previously, cache invalidation could cause recursion in cache processing.
PR #1493 fixed this for the

- cache_invalidate_callback() -> ts_extension_invalidate()

call path. But the call path
- cache_invalidate_callback() -> ts_extension_is_loaded()

could still go into recursion.

So, this PR moves the recursion-prevention logic into
extension_update_state(), which is common to both call paths.

Fixes #2200.

### CODE REVIEW

**Review by svenklemm — APPROVED** [review]

**Comment by erimatnor** [comment]
@cevian would be good to have a test case that reproduces the bug and shows that this is issue is fixed.

**Comment by cevian** [comment]
@erimatnor In theory I agree, but I haven't been able to come up with a reproducible case. This works most of the time as-is. It's some internal Postgres state that causes this behavior to be triggered.

**Comment by cevian** [comment]
@erimatnor I spent a lot more time trying to reproduce and could not. It seems like the loop is within `ReceiveSharedInvalidMessages` being execute at sinval.c:90 and sinval:120 (the latter every 32 = MAXINVALMSGS calls).
 
I think this only happens when there are a lot of msgs or something similar. I put my attempts at testing this in the fix_recursion_tests branch in my fork in case people want to get back to it at some point, but it feels like there is a benefit to merging this in the meantime.

**Review by pmwkaa — APPROVED** [review]
I wonder if it possible to write a test case for it

**Review by mkindahl — APPROVED** [review]
I think something is wrong with the cache code if we have to rely on these hacks to solve issues and I wonder how many more issues we have with the cache code. However, this solves the current problem and I do not see that this approach should cause any issues, so approving.

This seems to be a rare occurrence, so not sure how we can test this.

**Comment by cevian** [comment]
Leaving some more notes: I suspect this happens in the UNKNOWN state and in background workers. The backend causing the invalidation needs to commit or abort to cause invalidations to be sent to other workers. The bg workers has to also already be in a transaction when the messages are received, otherwise it will just happily stay in the unknown state.

Another note: scanning for the namespace in the heap instead of through cache will not help. The backtrace shows that the recursion happens through LockRelationOid, which would be called for a pure-heap scan too. Notice that the backtrace is for a cache miss.

**Pull request merged**
