### PR TITLE
Rename process_add_hypertable()

### PR DESCRIPTION
**Pull request by pmwkaa**
This function is implemented in the process utility hook and used to
form a list of hypertables to pass to the tsl module for further
processing. Mostly used in the distributed DDL implementation.

This change renames the function to a more obvious name, regarding
what it does: `add_for_tsl_ddl_command_start()`.

### CODE REVIEW

**Review by erimatnor — APPROVED** [review]

**Review by k-rus — COMMENTED** [review]
IMHO new name doesn't help much. It is complicated and can be violated by using it in non-tsl functionality. It also doesn't say what it does.
What's about:
```
add_hypertable_to_process_args
```

**Comment by pmwkaa** [comment]
> IMHO new name doesn't help much. It is complicated and can be violated by using it in non-tsl functionality. It also doesn't say what it does.
> What's about:
> 
> ```
> add_hypertable_to_process_args
> ```

Process utility hook handling start from `timescaledb_ddl_command_start` function, we have a cross function named `ddl_command_start` as well. I believe this name should be represented here as well.

The purpose of this function is to create a list of involved hypertables in utility query and pass it further to the tsl module.

**Comment by pmwkaa** [comment]
Any other thoughts?

**Comment by k-rus** [comment]
IMHO the function name should talk about what it does. It doesn't need to mention where it can be used, especially if it is not required for the function to work correctly. 

>Process utility hook handling start from timescaledb_ddl_command_start function, we have a cross function named ddl_command_start as well. I believe this name should be represented here too.

I don't see anything in its implementation, which required to mention in the name that it is used in process start.

> The purpose of this function is to create a list of involved hypertables in the utility query and pass it further to the tsl module. 

The function only adds one hypertable to the arg list of hypertables.

**Review by svenklemm — APPROVED** [review]

**Comment by pmwkaa** [comment]
@k-rus agree with you reasoning to use `add_hypertable_to_process_args` also make sense

**Review by k-rus — APPROVED** [review]

**Pull request merged**
