### PR TITLE
Add hypertable support for transition table

### PR DESCRIPTION
**Pull request by mkindahl**
This adds support for using statement-level triggers with transition tables to hypertables and chunks of hypertables.

### CODE REVIEW

**Comment by fabriziomello** [comment]
Did u see that there's an WIP PR for it? https://github.com/timescale/timescaledb/pull/6901

**Comment by mkindahl** [comment]
> Did u see that there's an WIP PR for it? #6901

Yes, I can push it there instead if you prefer that.

**Comment by mkindahl** [comment]
> > Did u see that there's an WIP PR for it? #6901
> 
> Yes, I can push it there instead if you prefer that.

Pushed to that branch.

**Comment by mkindahl** [comment]
Closing in favor of #6901

**Pull request closed without merging**
