### PR TITLE
Ignore flaky test for now

### PR DESCRIPTION
**Pull request by k-rus**
continuous_aggs_policy is flaky and prevents to proceed with current
PRs. This commit ignores it until it is fixed.

##PR note:
GH has problem with apprveyor.yml and shows diff for no changes.

### CODE REVIEW

**Comment by erimatnor** [comment]
My guess is that there's a windows vs. unix line ending diff in Appveyor.yml. It should be possible to fix in that case.

**Comment by k-rus** [comment]
> My guess is that there's a windows vs. unix line ending diff in Appveyor.yml. It should be possible to fix in that case.

@erimatnor do you mean that the diff in the line endings confuses GH?

**Review by mkindahl — APPROVED** [review]
Not entirely sure that it's a good idea to ignore an error is such a critical test, but approving since it's hard to get PRs in otherwise.

**Review by pmwkaa — APPROVED** [review]

**Comment by k-rus** [comment]
> My guess is that there's a windows vs. unix line ending diff in Appveyor.yml. It should be possible to fix in that case.

Actually, I think it was git who was fixing line endings.

**Pull request merged**
