### PR TITLE
CMake check for necessary testing tools

### PR DESCRIPTION
**Pull request by mkindahl**
Adding checks for `pg_isolation_regress` and `pg_regress` and not
running the tests if the programs cannot be found either installed in
default directories or provided with the `PG_PATH` variable, or the
`PG_SOURCE_DIR` variable.

### CODE REVIEW

**Comment by k-rus** [comment]
Do I understand correctly that after this change if something is wrong with CI setup so the program is not found, the tests will not be run and it is unlikely to be noticed?

**Comment by mkindahl** [comment]
> Do I understand correctly that after this change if something is wrong with CI setup so the program is not found, the tests will not be run and it is unlikely to be noticed?

Yeah, that is right. I was thinking the same, so will fix it.

**Comment by mkindahl** [comment]
> Looks good, but @k-rus makes a good point about Travis silently failing to run these tests in case of missing tools (due to config error, etc.). Perhaps we should add a config flag that ensures a hard failure in case of missing tools, e.g.., `-DFORCE_REGRESS_TOOLS_PRESENT=true`

Seems like a good approach.

**Comment by mkindahl** [comment]
I added an option so that by default regression checks are enabled, but they can be disabled. PTAL.

**Comment by mkindahl** [comment]
> LGTM
> As I see, the regress is ON by default and is OFF for docker builds and one project for Travis, but not for the main one. I expect that it is correct places where it is disable (but cannot judge myself) and it might be good to link the discussion/decision to this PR.

Yes, I had a few failures because these did not provide the regress tools, hence I disabled the regress checks for these tests. Hence all the pushes.

**Pull request merged**
