### PR TITLE
[Bug]: Fix segfault in ts_chunk_constraints_insert_metadata

### PR DESCRIPTION
**Pull request by kgyrtkirk**

### CODE REVIEW

**Review by svenklemm — CHANGES_REQUESTED** [review]
Isnt that a problem in the caller when constraints is NULL? This needs a tests.

**Comment by kgyrtkirk** [comment]
@svenklemm it would make sense to create a test - however so far I was not able to reproduce the original issue:
* it happened after upgrade
* based on the coredump other observations ccs was 0
* there are 2 ways to fix this
** add a nullcheck like in the current patch
** remove the >0 check [here](https://github.com/timescale/timescaledb/blob/65078486025a5cfdd00663f524831619066c5946/src/chunk.c#L1498) so that the constraints field is populated for 0 constraints as well

based on the above decrease in coverage probably the latter is more fortunate

**Comment by kgyrtkirk** [comment]
@mkindahl could you please share your point of view?

**Comment by mkindahl** [comment]
> @mkindahl could you please share your point of view?

Regarding the pull request, you are missing a reference to the issue that this solves, so would suggest that you add one so that we can see that the PR is related to it.

The problem occurs during an upgrade probably because the constraints are added late in the process so the hypertable does not have constraints at this point. I am not sure how you tested the upgrade, but given customer comments, it seems to be triggered by dumping one version and restoring on another version.

Now, we should clearly not have a segmentation fault while upgrading, so there are a few questions that might be good to have a look into:

- Can this happen in other situations that are not upgrades? In particular, since constraints are added late in the dumped script, it is entirely possible that if a constraint is dropped from a hypertable by accident, it will trigger the issue, which would then give you a reproduction case and possibly require more work to fix the issue. It would be good to know that is not the case.
- Since this is triggered by our code, not by PostgreSQL code, and `pg_restore` should be executed with `timescaledb.restoring` set to `off`, does this mean that the user is running the `pg_restore` with `timescaledb.restoring` set to `on`?

**Pull request closed without merging**
