### PR TITLE
Use America/Los_Angeles in tests instead of PST8PDT

### PR DESCRIPTION
**Pull request by akuzm**
Follow the PG upstream changes in light of the upcoming timezone updates. This should fix our regression tests on latest PG snapshots.

https://github.com/postgres/postgres/commit/2b94ee58bf256e1b4682f21f13d0f2c73e1b0cc2

Example of the failing test on main: https://github.com/timescale/timescaledb/actions/runs/11666186287/job/32480586544

Disable-check: force-changelog-file

test

### CODE REVIEW

**Comment by svenklemm** [comment]
Setting the timezone in all the cagg files was a workaround for a problem with cagg refresh which has been fixed so we can probably remove the explicit timezone from the cagg test files again.

**Comment by akuzm** [comment]
> Setting the timezone in all the cagg files was a workaround for a problem with cagg refresh which has been fixed so we can probably remove the explicit timezone from the cagg test files again.

Removed.

**Review by erimatnor — APPROVED** [review]
I assume you grepped for `PST8PDT` or `set timezone` to find all instances?

**Comment by akuzm** [comment]
> I assume you grepped for `PST8PDT` or `set timezone` to find all instances?

Yep

**Review by svenklemm — APPROVED** [review]

**Pull request merged**
