### PR TITLE
Highlight that PG_CONFIG can be used to specify the path to the Postg…

### PR DESCRIPTION
**Pull request by jesperpedersen**
…reSQL installation.

### CODE REVIEW

**Comment by RobAtticus** [comment]
@jesperpedersen if you rebase this I'll go ahead and merge. Thanks for these PRs!

**Comment by jesperpedersen** [comment]
@RobAtticus Done

**Comment by RobAtticus** [comment]
Thanks!

**Comment by jesperpedersen** [comment]
Thanks !

**Pull request merged**
