### PR TITLE
[PG10] Handle already partitioned table on create_hypertable()

### PR DESCRIPTION
**Pull request by jwdeitch**
Hi, 

This error was encountered when defining a table with partitioning, and then calling create_hypertable() (on master, timescale repo, docker build process):

`[42809] ERROR: cannot create index on partitioned table "temps" Where: SQL statement " CREATE INDEX ON public.temps("time" DESC) " PL/pgSQL function _timescaledb_internal.create_default_indexes(_timescaledb_catalog.hypertable,regclass,name) line 29 at EXECUTE SQL statement "SELECT _timescaledb_internal.create_default_indexes(hypertable_row, main_table, partitioning_column)" PL/pgSQL function public.create_hypertable(regclass,name,name,integer,name,name,anyelement,boolean,boolean,regproc) line 102 at PERFORM`

this PR serves to raise exception on create_hypertable() under this condition.

---

`SELECT create_hypertable(temps); ALTER TABLE temps ADD PARTITION time;`

The above does not produce any issues on my end so I am curious to know the intended interop with PG10 partitions and hypertables

### CODE REVIEW

**Comment by RobAtticus** [comment]
Seems reasonable to me, and the question is a good one. Will let @erimatnor or @cevian take a look.

**Comment by erimatnor** [comment]
@jwdeitch I am going to merge this.

**Comment by jwdeitch** [comment]
Sure thing - I'll implement this test case and rebase

**Comment by jwdeitch** [comment]
@erimatnor should be good to go on my end

@cevian Looks like the testing scripts run against pg9.6 - might not want to change the docker script to 10.0 as it might not cover regressions in 9.6. I will try to create a docker script that can run 9.6 and 10 tests in parallel this week.

**Pull request merged**
