### PR TITLE
Set C standard to C11

### LINKED ISSUE #867: CMake should require C99 support
When compiling from source, older gcc's (e.g. gcc-4.8) fail to compile some files, because C99 support isn't explicitly required via cflags (and falls back to C90)

A quick fix is to add this to ./CmakeLists.txt:
`set(CMAKE_C_STANDARD 99)`

(but there's probably a more robust solution: https://cmake.org/cmake/help/v3.1/prop_tgt/C_STANDARD.html)

### PR DESCRIPTION
**Pull request by svenklemm**
Fixes #867

### CODE REVIEW

**Comment by RobAtticus** [comment]
Taking myself off review, I have no special input here (not a C compiler guy, nor cmake guru)

**Comment by erimatnor** [comment]
FWIW, isn't C99 mostly backwards compatible with earlier standards? So, in what way is our code not compliant? @JLockerman

**Comment by JLockerman** [comment]
@erimatnor There are two issues:  
The smaller one is GNU extensions¹, a bunch of which have crept into the codebase. I'm honestly not too worried about these, since I postgres itself uses many of them, and they seem pretty well supported.
The bigger issue is that _C11_ features have snuck into the codebase, probably because the version of `clang` most of us use builds against C11 by default. Right now it looks like the only ones showing up is `typedef-redefinition`, which I don't think is too important.  
(I'm also a _little_ concerned that since we've been doing all our testing on C11, we'll be bitten by some subtle semantic change by switching to C99, specifically due to changes in the C memory model to support multithreading. Since all our concurrency primitives are from postgres, they're theoretically compatible, and hopefully our tests would catch anything else. Unfortunately, I don't see a could way to check for this besides just trying)

Given that a bunch of platforms, including RHEL6, are still on a gcc earlier than 4.6, I think I'm ok with switching to `-std=gnu99` on all Unixes, as long as we also add `-pedantic` and explicitly whitelist the extensions we're using, so more C11 features don't sneak in. I'd want one of us to look over Windows C compatibility before switching it there, I know that it wasn't posix compliant until msvc17, but I don't know if they switched the entire CRT or just the one for C11.

@svenklemm you okay adding the flags? They're `-Wno-<warning name>` and go in `src/build-defs.cmake`

¹ The list of gnu extensions I've had to whitelist is  
`gnu-statement-expression`, `gnu-statement-expression`, `gnu-zero-variadic-macro-arguments`, `language-extension-token`, `gnu-empty-initializer`, `extra-semi`, `flexible-array-extensions`

**Comment by JLockerman** [comment]
@svenklemm reading through the [cmake docs](https://cmake.org/cmake/help/v3.1/prop_tgt/C_STANDARD.html) it looks like cmake will fall back to an earlier standard if the current one isn't available. Would you be willing to have this PR switch setting the standard to `11`? That way we'll have the same behavior on targets that currently work, and we should fall back gracefully on targets that only support earlier standards. We can discuss exactly what to enforce by the compiler later.

**Pull request merged**
