### PR TITLE
Check GRANTs in update tests

### PR DESCRIPTION
**Pull request by svenklemm**
Currently the update tests do not compare grants between update and new install, this patch adds grants to the compared state.

### CODE REVIEW

**Comment by RobAtticus** [comment]
Seems right to me, wait for @cevian to approve

**Comment by erimatnor** [comment]
should the title be "Check GRANTs in update tests"?

**Comment by svenklemm** [comment]
This can't be applied straight away cause at least 1.0rc1 to 1.0rc2 is missing grants in the update script.

**Comment by erimatnor** [comment]
@svenklemm commit log still has "checks" instead of "tests" :)

**Pull request merged**
